version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    image: pf-backend-mock:latest
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    image: pf-frontend:latest
    environment:
      # Por ahora apuntamos al backend mock en la red del compose
      - BACKEND_URL=http://backend:3000
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
