services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    image: pf-mock-backend:latest
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    image: pf-frontend:latest
    environment:
      # Apunta al mock backend interno del compose
      - BACKEND_URL=${BACKEND_URL:-http://backend:3000}
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
